{"uuid": "d9862551-22ea-4559-8d45-a65259d23d74", "children": ["613ca045-bf03-40d2-a569-20c8a62042e1"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "KeyError: 'is_run'\n", "trace": "  File \"/Users/nali/anaconda3/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/nali/anaconda3/lib/python3.7/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/nali/anaconda3/lib/python3.7/site-packages/_pytest/fixtures.py\", line 792, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/nali/AutoApiTest/conftest.py\", line 28, in login\n    api_send_check(request.param, case_dict, case_path, relevance)\n  File \"/Users/nali/AutoApiTest/common/unit/api_send_check.py\", line 24, in api_send_check\n    if case_data['is_run'] is not False:\n"}, "start": 1617289344781, "stop": 1617289344782}], "start": 1617289344781, "stop": 1617289344792}