{"uuid": "2597e314-8da0-4a66-8116-1a37a2d597b9", "children": ["91bbc5f5-69a6-4233-8301-9a8b2c5849b7", "3ee52d92-960c-4685-bc9c-5cddb89d4725", "4bf1df89-1b39-4cbb-ae11-c70a705fcc59", "354da53a-84be-45a2-8e42-a8d1e265ca9d", "2d1841a2-67df-4c2d-afc5-c5edce3e278c", "00cb865e-2050-4d4f-8483-95c67da997f4", "516820f7-a4fd-40c0-96b6-95d7a19035e0", "5afbd527-6e6a-4aa1-a147-ea8679f34a50", "7bcc8b69-5bff-4acc-b90b-32df36021e20", "aee63354-f2b1-4eaa-88b3-642b264dfc91", "2b696f52-d95d-4185-8333-7a86fda4d316", "ed62b70f-7f88-4ecc-8e1d-16b532b29493", "dc8cc98d-cb1d-49b3-830e-9c9896b14c42", "fc437100-47c7-4f96-9d0c-0fe6df9836c8", "b0a35188-16d8-444b-ae94-4f56ca50b5a4", "ceb6f75f-2a44-4333-9136-05c8f6915ce1", "6315dbbf-4b23-4fb5-b6d9-16de980aa66b", "f9085607-c3da-4062-9032-8c882734a154", "42c65788-b73b-45f1-bace-99cccb1f40b6"], "befores": [{"name": "setup_env", "status": "broken", "statusDetails": {"message": "AttributeError: module 'allure' has no attribute 'environment'\n", "trace": "  File \"/Users/nali/anaconda3/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/nali/anaconda3/lib/python3.7/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/nali/anaconda3/lib/python3.7/site-packages/_pytest/fixtures.py\", line 792, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/nali/AutoApiTest/conftest.py\", line 22, in setup_env\n    allure.environment(测试环境=\"测试环境\", hostName=Host[\"HOST2\"], 执行人=\"安琪\", 测试项目=\"m站线上接口测试\")\n"}, "start": 1617807207048, "stop": 1617807207048}], "start": 1617807207047, "stop": 1617807207336}