{"uuid": "caa0cd30-2e88-40b4-9358-0059b8de367c", "children": ["33c8e270-75aa-48fd-8c5b-c52a28af9f64", "fabebac2-5cc1-4e99-a297-f28045e0a592", "9b0e8a1b-3a4e-45cb-8c27-519212d7347c", "78d6a729-8fd5-43f8-a1bf-6229edc669e8", "7f0fdafc-4d45-4b60-816b-ebfcb48497af", "4ff98ea2-9823-49dd-8390-33690119c67d", "158b301c-68c3-4e0a-96c4-7347460514a9", "45d6f9f9-5f81-4413-bf03-7ec90aaa5f82", "61222c7c-525d-460a-8828-3ac1a306e456", "bf8ee637-06bd-4137-ba01-bbf478dc2962", "18e50509-9a1b-4c56-9297-4b6672f80d5d", "5d431e84-80fc-43de-9a81-145be5799a9f", "01eec315-3d4c-47b8-b165-0e515fb5916e", "5d93107d-1a3a-4d48-87d9-8a319fc110a3", "651f5e6a-001d-4366-8410-bf4df12e33d8", "ab3f5906-b872-46dd-99f7-8e0dd7cc41d9", "f83c9465-372c-4baa-9d4f-08355a41b822", "a518c821-8893-4c21-a493-906d3af0432c", "88d73a5c-3b5e-4f56-ab53-40320c0ceaaf"], "befores": [{"name": "setup_env", "status": "broken", "statusDetails": {"message": "AttributeError: module 'allure' has no attribute 'environment'\n", "trace": "  File \"/Users/nali/anaconda3/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/nali/anaconda3/lib/python3.7/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/nali/anaconda3/lib/python3.7/site-packages/_pytest/fixtures.py\", line 792, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/nali/AutoApiTest/conftest.py\", line 22, in setup_env\n    allure.environment(测试环境=\"测试环境\", hostName=Host[\"HOST2\"], 执行人=\"安琪\", 测试项目=\"m站线上接口测试\")\n"}, "start": 1618288546180, "stop": 1618288546180}], "start": 1618288546180, "stop": 1618288546460}